version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=dialektorlocaldb
      - POSTGRES_USER=dialektoruser
      - POSTGRES_PASSWORD=password
  web:
    container_name: web
    build: .
    environment:
      - DATABASE_URL
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db