version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=dialektorlocaldb
      - POSTGRES_USER=dialektoruser
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_web
    environment:
      - DATABASE_URL
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db